name: Publication Docker image Php
on:
  push:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Cache Docker Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile  # Spécifiez le chemin vers votre Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64, linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/ffsend:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Run Docker Container to Generate Output
        run: |
          mkdir -p output  # Créez le répertoire output s'il n'existe pas
          for platform in linux/amd64 linux/arm64; do
            docker run --rm --platform $platform -v $(pwd)/output:/output ${{ secrets.DOCKER_USERNAME }}/ffsend:latest
            mv output/ffsend output/ffsend-$(echo $platform | sed 's/\//-/g')
          done
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/ffsend*  # Spécifiez le chemin vers le fichier à mettre en release
          tag_name: ffsend:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisez le token GitHub pour créer une release